[package]
authors = ["Shinyzenith <https://shinyzenith.xyz>"]
description = "Screenshot tool for wlroots based compositors implementing the zwlr_screencopy_v1 protocol."
documentation = "https://docs.rs/crate/wayshot/latest"
edition = "2021"
homepage = "https://waycrate.shinyzenith.xyz"
keywords = ["screenshot", "wayland", "wlroots"]
license = "BSD-2-Clause"
name = "wayshot"
repository = "https://git.sr.ht/~shinyzenith/wayshot"
version = "1.1.9"
exclude = [
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
	"contrib/*",
	"docs/*",
	"release.sh",
]

[dependencies]
clap = "3.1.18"
env_logger = { version = "0.9.0", default-features = false, features = ["atty", "termcolor"] }
image = { version = "0.24", default-features = false, features = ["jpeg", "png", "pnm"] }
log = "0.4.17"
memmap2 = "0.5.3"
nix = "0.24.1"
wayland-client = "0.29.4"
wayland-protocols = { version = "0.29.4", features=["unstable_protocols", "client"] }
tempfile = "3.3.0"

[[bin]]
name = "wayshot"
path = "src/wayshot.rs"
